
package VisaoCadastrar;


import DAO.CategoriaDAO;
import DAO.Conexao;
import DAO.LivroDAO;
import Modelo.Categoria;
import Modelo.Livro;
import Principal.Menu;
import java.io.IOException;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Valéria
 */
public class CadastrarLivro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastra
     */
    public CadastrarLivro() {
        initComponents();
        setSize(700, 450);
        setLocationRelativeTo(this);
        AtualizarCombo();
         
    }
    
 private void AtualizarCombo(){
    Connection con = Conexao.AbrirConexao();
    CategoriaDAO sql = new CategoriaDAO(con);
    List<Categoria> lista = new ArrayList<>();
    lista =  sql.ListarComboCategoria();
    for(Categoria c : lista){
       ComboCategoria.addItem(c.getCategoria()); 
    }
    Conexao.FecharConexao(con);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nome = new javax.swing.JTextField();
        valtar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idCategoria = new javax.swing.JTextField();
        ComboCategoria = new javax.swing.JComboBox<>();
        resumo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cadastra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        getContentPane().add(nome);
        nome.setBounds(170, 90, 400, 30);

        valtar.setBackground(new java.awt.Color(255, 204, 0));
        valtar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        valtar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/voltar.png"))); // NOI18N
        valtar.setText("VOLTAR");
        valtar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valtarActionPerformed(evt);
            }
        });
        getContentPane().add(valtar);
        valtar.setBounds(130, 340, 156, 51);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("NOME DO LIVRO:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 80, 130, 40);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("CATEGORIA:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 130, 120, 30);

        idCategoria.setEditable(false);
        getContentPane().add(idCategoria);
        idCategoria.setBounds(170, 130, 90, 30);

        ComboCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboCategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(ComboCategoria);
        ComboCategoria.setBounds(280, 130, 290, 30);
        getContentPane().add(resumo);
        resumo.setBounds(170, 180, 410, 120);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("RESUMO:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 180, 110, 30);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRO DE LIVROS:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 10, 540, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 60);

        jPanel2.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/nova2.jpg"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 710, 270);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 60, 800, 270);

        jPanel3.setLayout(null);

        cadastra.setBackground(new java.awt.Color(102, 255, 51));
        cadastra.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cadastra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ok.png"))); // NOI18N
        cadastra.setText("CADASTRAR");
        cadastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastraActionPerformed(evt);
            }
        });
        jPanel3.add(cadastra);
        cadastra.setBounds(390, 10, 156, 51);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 330, 710, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastraActionPerformed
      String No = nome.getText();
      String idCat = idCategoria.getText();
      String res = resumo.getText();
        if (nome.equals("")) {
               JOptionPane.showMessageDialog(null, "Nenhum campo pode está vazio.", "Sistema", JOptionPane.WARNING_MESSAGE);
        } else {
            Connection con = Conexao.AbrirConexao();
             LivroDAO sql = new LivroDAO(con);
            int id = Integer.parseInt(idCat);
            Livro c = new Livro();
            c.setNome(No);
            c.setIdcategoria(id);
            c.setResumo(res);
            sql.InserirLivro(c);
            Conexao.FecharConexao(con);
            JOptionPane.showMessageDialog(null, "Cadastro concluido!", "Sistema", JOptionPane.INFORMATION_MESSAGE);
             new Menu().setVisible(true);
        dispose();
        } 
    }//GEN-LAST:event_cadastraActionPerformed

    private void valtarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valtarActionPerformed
          new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_valtarActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void ComboCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCategoriaActionPerformed
      Connection con = Conexao.AbrirConexao();
    CategoriaDAO sql = new CategoriaDAO(con);
    List<Categoria> lista = new ArrayList<>();
    String nome = ComboCategoria.getSelectedItem().toString();
    
    lista = sql.ConsultaCodigoCategoria(nome);
    
    for(Categoria c: lista){
        int a = c.getId();
        idCategoria.setText("" + a);    
    }
    Conexao.FecharConexao(con);  
    }//GEN-LAST:event_ComboCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarLivro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboCategoria;
    private javax.swing.JButton cadastra;
    private javax.swing.JTextField idCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField resumo;
    private javax.swing.JButton valtar;
    // End of variables declaration//GEN-END:variables
}
